version: '3'
services:

  # Servidor Node.js
  nodejs:
    container_name: vallidator-app
    image: node:18-alpine
    volumes:
      - ./Vallidator:/app #
    ports:
      - "3000:3000" # Mapeia a porta do contêiner para a porta local
    working_dir: /app/backend
    command: # Comando para iniciar servidor Node.js
      - sh
      - -c
      - |
        npm install
        npm start
    depends_on:
      - postgres
      - pgadmin
    restart: always
    

  # Banco de Dados PostgreSQL
  postgres:
    container_name: vallidator-db
    image: postgres:13 
    environment:
      POSTGRES_DB: vallidatordb 
      POSTGRES_USER: kapouser 
      POSTGRES_PASSWORD: senhakapo 
    volumes:
      - ./data:/var/lib/postgresql/data # Volume para persistência de dados

  # Ferramenta de Administração do PostgreSQL (Opcional)
  pgadmin:
    container_name: my-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kaique.govani@hotmail.com 
      PGADMIN_DEFAULT_PASSWORD: admin