GET http://localhost:3000/templates/listar
###
GET http://localhost:3000/templates
###
POST http://localhost:3000/templates/criar
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGVybWlzc2FvIjoiYWRtaW4iLCJpYXQiOjE2OTY0ODgyMDMsImV4cCI6MTY5NjQ5MTgwM30.klyxJqOWB7ir_O9dSwaVA_2gaX3l4gaGd54smEe6o0A

###
POST http://localhost:3000/templates/criar
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGVybWlzc2FvIjoiYWRtaW4iLCJpYXQiOjE2OTY0ODgyMDMsImV4cCI6MTY5NjQ5MTgwM30.klyxJqOWB7ir_O9dSwaVA_2gaX3l4gaGd54smEe6o0A

{
    "nome": "ExemploTemplate0",
    "id_criador": 1,
    "extensao": "csv",
    "status": true,
    "campos": [
      {
        "nome_campo": "Campo1",
        "tipo_campo": "Texto",
        "anulavel": false
      },
      {
        "nome_campo": "Campo2",
        "tipo_campo": "Texto",
        "anulavel": false
      },
      {
        "nome_campo": "Campo3",
        "tipo_campo": "Texto",
        "anulavel": false
      },
      {
        "nome_campo": "Campo4",
        "tipo_campo": "Texto",
        "anulavel": false
      }
    ]
}
###